import { StyleSheet, Dimensions } from "react-native";

const CommonStyle = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#edfaf6',
    paddingTop: '10%',
    paddingBottom: '30%',
    height: '100%',
  },
  safeContainerStyle: {
    margin: 30,
    justifyContent: 'center',
  },
  wrapper: {
    width: '80%',
    height: '100%',
  },
  textboxid: {
    backgroundColor: 'white',
    borderBottomColor: 'gray',
    borderBottomWidth: 0.5,
    borderRadius: 6,
    fontSize: 14,
  },
  textboxInput: {
    backgroundColor: 'white',
    borderRadius: 6,
    fontSize: 14,
    paddingLeft: 10,
    height: 50,
  },
  input: {
    backgroundColor: 'white',
    borderBottomColor: 'gray',
    borderRadius: 6,
    fontSize: 14,
    height: 50,
  },
  image2: {
    width: '60%',
    height: Dimensions.get('window').height / 4.3,
    marginBottom: '5%',
    alignSelf: 'center',
  },
  errtxt: {
    color: 'red',
    padding: 10,
    marginBottom: 5,
    marginVertical: 0,
    paddingVertical: 0,
    fontSize: 14,
  },
  titletxt: {
    fontSize: 30,
    textAlign: 'center',
    padding: 0,
    color: '#167D7F',
    borderRadius: 6,
    borderColor: '#ff623c',
    fontFamily: 'SourceSerif4-Regular',
  },
  btnlogin: {
    marginTop: 13,
  },
  button02: {
    justifyContent: 'center',
    width: Dimensions.get('window').width / 2.2,
    backgroundColor: '#167D7F',
    borderRadius: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.9,
    shadowRadius: 4,
    elevation: 10,
    height: 50,
    margin: 10,
  },
  mapButton: {
    backgroundColor: '#167D7F',
    borderRadius: 20,
    padding: 7,
    margin: 10,
    shadowColor: '#303838',
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 10,
    shadowOpacity: 0.35,
  },
  button03: {
    justifyContent: 'center',
    width: Dimensions.get('window').width / 1.8,
    backgroundColor: '#00c292',
    borderRadius: 6,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.9,
    shadowRadius: 4,
    elevation: 10,
    height: 50,
    marginTop: 13,
  },
  dropdown: {
    backgroundColor: 'white',
    borderBottomColor: 'gray',
    borderBottomWidth: 0.5,
    marginTop: 20,
    padding: 5,
  },
  shadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  buttonText: {
    fontSize: 18,
    textAlign: 'center',
    margin: 10,
    color: '#ffffff',
    backgroundColor: 'transparent',
    fontFamily: 'SourceSerif4-Regular',
    padding: 0,
  },
  separator: {
    marginVertical: 10,
  },
  link: {
    color: '#167D7F',
  },
});

export { CommonStyle };